[package]
name = "example-basics-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_wallet = { version = "1.0.0-beta.5", features = ["keys-bip39"] }
bdk_esplora = {  version = "0.19.0" , features = ["blocking"] }